spring:
  application:
    name: brms
com:
  keta:
    rule:
      directory: 'customer'
      cloned-directory: 'rules-git'
      git-url: 'https://github.com/keaz/drools-rules.git'
      git-userName: 'brms'
      git-token: 6ffe61722612c2afe45eb5c17aca42a11a941804
